### ISSUE TITLE
Processor Expert Dual Speed USB generated code missing speed detection

### ISSUE THREAD

**Issue by lucasrangit** [ErichStyger/McuOnEclipse_PEx#10]
I'm using Processor Expert 3.0.1.b150806, Kinetis Design Studio 3.0.0, and the KSDK 1.3.0 (1.0.0.b150914) and a K26 MCU. The MCU USB PHY supports high/full/low-speeds but the Processor Expert code does not produce code that works for High Speed.
 
The `fsl_usb_descriptor` options are "Low speed", "Full speed", and "Dual speed". Using Processor Expert to configure a Full-Speed USB descriptor (Device Speed) works. When configured for "Dual speed" both a "High speed" and a "Full speed" "Device description is created (I assume for backwards compatibility with USB 1.1).
 
An issue I found is the generated USB descriptor code (e.g. `usbDsc1.c:USB_Desc_Get_Descriptor()`) does not return the High Speed descriptor even when the USBHS_PORTSC1[HSP] indicates this is a High Speed port.
 
I suspect this is because there is no generated code that updates the variable `usbDsc1_CurrentUsbSpeed`, used by `usbDsc1.c:USB_Desc_Get_Descriptor()`, when the port is changed or reset.
 
As a workaround I added the following line to my main() before the Processor Expert's PE_low_level_init().
 
`usbDsc1_USB_Desc_Set_Speed(0, USB_SPEED_HIGH); // first argument is not used  
`

Is there a better way to fix this issue?
 
I could not find where the Processor Expert generated code comes from and patching the KSDK makes it difficult to version the project because changes are overridden by the KSDK installed on the developer's host. Can you point me in the right direction so I can put together a proper patch and validate it before sending it for review?

Reference post on Kinetis Forum: https://community.freescale.com/message/620651

**Comment by ErichStyger** [comment]
The components on this site are open and you can modify them. The ones delivered by Freescale/NXP are closed and encrypted, so you cannot change them. Well, at least most of them. To my understanding you cannot change any of the NXP delivered components. If they are open, here is an article showing where things are: http://mcuoneclipse.com/2012/06/30/cde-hacking-where-is-my-stuff-a-dissection/
But as you are not using the McuOnEclipse USB components, there is nothing I can for this ticket.

**Comment by lucasrangit** [comment]
Oh! Sorry for the noise, I assumed this was the same Processor Expert and that they were all open source.
