### ISSUE TITLE
Component module WAIT1

### ISSUE THREAD

**Issue by armgomes** [ErichStyger/McuOnEclipse_PEx#12]
Hi Erich!

Fitst all I'd like say thank you for your support. 

According to your advince, I'm write here about WAIT 1. In NXP community you wrote:

"Hi Arnaldo,
For me, the delay time are around 10 ms both for the internal clock and the clock configuration you have. Keep in mind that because it is using a number of nops to wait, the timing is in the ~10% range.
Below is the code for toggling the blue LED (PTD1) on the FRDM-KL25Z:
Default internal clock:
 
With your clock settings:
 
The number of wait cycles is based on the core clock:
  #define WAIT1_INSTR_CLOCK_HZ  	CPU_CORE_CLK_HZ /* for Kinetis, use core clock as base for instruction execution */
Which 48MHz in that configuration:
#define CPU_CORE_CLK_HZ            	48000000U /* Initial value of the core/system clock frequency in Hz.  */
 
I know there was an issue with what clock to be used (it used the bus clock instead of the the core clock) in a very old Wait component (about 2 years ago).
Are you really using the latest version from SourceForge (see https://mcuoneclipse.com/2014/10/21/mcuoneclipse-releases-on-sourceforge/ )?
 
In any case, I have attached my test project so you can compare the code and component version numbers.
 
I hope this helps,
Erich
 
PS: I recommend to report issues in the GitHub tracking system here: Issues · ErichStyger/McuOnEclipse_PEx · GitHub"

Affter install the Processor Expert Component Repositories, according to your post (https://mcuoneclipse.com/2015/07/06/processor-expert-component-repositories/). I found a new error: Component is not selected (SDK).

It' possible to use the WAIT1 without the SDK in project?

I tred to use WAIT1 in project with SDK, but don't worked showed the same error (Component is not selected (SDK)"

Do you have any tip?

Regards,
Arnaldo

**Comment by armgomes** [comment]
Hi Erich!

I found my mistake!!! Now works very well

Regards,

Arnaldo

**Comment by ErichStyger** [comment]
Hi Arnaldo,
thanks for the confirmation. As you probably have found out, the 'KinetisSDK' component can set to 'none', then it does not need any SDK.

Erich
