### ISSUE TITLE
RingBuffer

### ISSUE THREAD

**Issue by EliNaiman** [ErichStyger/McuOnEclipse_PEx#20]
I am using KDS 3.2.0 and the K64F board.
When I add the RingBuffer component from the 2016-10-30 release everything is OK
When I add the RingBuffer component from the 2016-12-12 release the generated code shows a problem related to the CS1 component.

**Comment by ErichStyger** [comment]
could you post the error message, or even better your project so I can have a look? You don't need to provide all the sources: all what I need are the project files with the .pe file.

**Comment by EliNaiman** [comment]
This is what I did using KDS 3.2.0 and component release 2016-10-30
- created a Processor Expert project
- added consoleIO component
- added Serial_LDD component
- added RingBuffer component
- I made changes to the clock settings to be able to handle the 115200 baud rate

Generating code via Processor Expert was OK.

I than imported the component release 2016-12-12 and regenerated the code.
That is where the CS1 error shows up.
[Test1.zip](https://github.com/ErichStyger/McuOnEclipse_PEx/files/670939/Test1.zip)

**Comment by EliNaiman** [comment]
I just want to add that I repeated the previous test but this time I set the clock according to your article
 "FRDM-K64F at Maximum Speed of 120 MHz". Again it works with the 2016-10-30 release but not with the 2016-12-12 release. I hope that helps.

**Comment by ErichStyger** [comment]
No, unfortunately this does not help, as I have no chance to reproduce or see your problem :-(. The zip file you have uploaded only has some generated files, but not the .pe and not the project files. Can you upload a complete project?

**Comment by EliNaiman** [comment]
I don't know how to upload a project onto GitHub
  
   ---------- Original Message ----------
   From: Erich Styger <notifications@github.com>
   Date: December 23, 2016 at 4:34 PM
   
   
   No, unfortunately this does not help, as I have no chance to reproduce or see your problem :-(. The zip file you have uploaded only has some generated files, but not the .pe and not the project files. Can you upload a complete project?

**Comment by EliNaiman** [comment]
I downloaded the Git Desktop app and I think I created a repository there that contains the project. It is called Test1.
  Sorry, but I am new to this and I hope it worked.
  
   ---------- Original Message ----------
   From: Erich Styger <notifications@github.com>
   Date: December 23, 2016 at 4:34 PM
   
   
   No, unfortunately this does not help, as I have no chance to reproduce or see your problem :-(. The zip file you have uploaded only has some generated files, but not the .pe and not the project files. Can you upload a complete project?

**Comment by ErichStyger** [comment]
You can zip the project (as you did with the files earlier) and upload that zip.

**Comment by ErichStyger** [comment]
Where is that repository with that Test1 project?

**Comment by EliNaiman** [comment]
@ https://github.com/EliNaiman/Test1
  
   ---------- Original Message ----------
   From: Erich Styger <notifications@github.com>
   Date: December 24, 2016 at 3:39 AM
   
   
   Where is that repository with that Test1 project?

**Comment by ErichStyger** [comment]
that repository is empty?

**Comment by EliNaiman** [comment]
I think I finally was able to upload to GitHub. There are 2 repositories:
  https://github.com/EliNaiman/RingBuffer2016-12-12
  https://github.com/EliNaiman/RingBuffer2016-10-30
  I hope it helps. I am using the 2016-10-30 release.
  
   ---------- Original Message ----------
   From: Erich Styger <notifications@github.com>
   Date: December 25, 2016 at 1:31 AM
   
   
   that repository is empty?

**Comment by ErichStyger** [comment]
Now this helps. I'm trying the 2016-12-12 repository, and your components in there are not using the latest version from SourceForge, as your components are still using the KinetisSDK component. You need to fix your component settings and select the McuLibConfig component instead of the Kinetis SDK one, and remove the Kinetis SDK one. I did that for your project, and then it generates code and compiles just fine. As explained in the article about the new components.
I have attached the fixed project.

I hope that this makes sense? Or is there another problem I don't see?


[RingBuffer2016-12-12-master.zip](https://github.com/ErichStyger/McuOnEclipse_PEx/files/672308/RingBuffer2016-12-12-master.zip)

**Comment by ErichStyger** [comment]
closing the issue as I think it has been resolved, thanks.
