### ISSUE TITLE
K64F and UART1

### ISSUE THREAD

**Issue by EliNaiman** [ErichStyger/McuOnEclipse_PEx#21]
I am working with KDS 3.2.0 and the K64F board.
Flow control does not seem to work with UART1. If I disable flow control, the UART works but I get some bad characters. I am only using 9600 baud.

**Comment by ErichStyger** [comment]
Which component are you using? The AsynchroSerial one? In that case, I won't be able to help, as this one is provided by NXP and the sources are not open for it. As a general comment: I have not used hardware flow control in my projects.

**Comment by ErichStyger** [comment]
Is there any more information available? Otherwise, I'm closing the issue.
