### ISSUE TITLE
Incompatibility in type definition

### ISSUE THREAD

**Issue by martin-mm** [ErichStyger/McuOnEclipse_PEx#22]
Hi Erich,

I used the FATFS and a CDC in a Kinetis-Design-Studio project (Freescale-NXP-Qualcomm :-) K60) with IAR EWARM compiler. There seems to be a problem with including "integer.h" by "diskio.h" and generated "types.h" included elsewhere:

In "integer.h" the typedef for BYTE is: typedef unsigned char	BYTE;
In "types.h" the typedef for BYTE is:
typedef union _BYTE
{
    uint_8 _byte;
    struct
    {
        unsigned b0:1;
        unsigned b1:1;
        unsigned b2:1;
        unsigned b3:1;
        unsigned b4:1;
        unsigned b5:1;
        unsigned b6:1;
        unsigned b7:1;
    }Bit;
} BYTE;

Same problem with WORD and DWORD.

types.h is included by gererated "CDCx.c" and generated "hidef.h". Whereas in hidef.h this depends on the compiler that has been used, in CDCx.c it does not.

Best regards

Martin

**Comment by ErichStyger** [comment]
Hi Martin,
I admit, I have not used IAR for a while. I have checked types.h and it seems that thee types BYTE, WORD and DWORD are not used in the USB stack. I have disabled them now (see https://github.com/ErichStyger/McuOnEclipse_PEx/commit/06f4d9f7ed1f96449afd63d71a914f03f238189b). I think that's the correct fix and this should work for you as well. Can you confirm?

Thanks,
Erich

**Comment by martin-mm** [comment]
Hi Erich,

 

Unfortunately I still get the error. Will investigate.

 

I found another tricky one:

 

CLSx.c:

 

unsigned CLS1_printfIO(CLS1_ConstStdIOType *io, const char *fmt, ...)

{

  va_list args;

  unsigned int count = 0;

 

  va_start(args,fmt);

  count = XF1_xvformat(CLS1_printfPutChar, io->stdOut, fmt, args);

  va_end(args);

  return count;

}

 

Here IAR complains about casting a function pointer to void * (seems that GCC is more relaxed here)

 

Should be casted in the CLSx.c:

 

unsigned CLS1_printfIO(CLS1_ConstStdIOType *io, const char *fmt, ...)

{

  va_list args;

  unsigned int count = 0;

 

  va_start(args,fmt);

  count = XF1_xvformat(CLS1_printfPutChar, (void *)(io->stdOut), fmt, args);

  va_end(args);

  return count;

}

 

And a third one:

 

MCUx.h includes Cpu.h:

 

#if MCUC1_CONFIG_SDK_VERSION_USED == MCUC1_CONFIG_SDK_PROCESSOR_EXPERT

/* Include shared modules, which are used for whole project */

  #include "PE_Types.h"

  #include "PE_Error.h"

  #include "PE_Const.h"

  #include "IO_Map.h"

  #include "Cpu.h" /* include CPU related interfaces and defines */

 

Cpu.h includes PE_Types.h which includes <stdint.h> which includes <yvals.h>

 

The problem with the IAR is now that portasm.s includes FreeRTOSConfig.h which includes MCUx.h.

Yvals.h now can only be used with the compiler but not with the assembler:

 

#if (__IAR_SYSTEMS_ICC__ < 8) || (__IAR_SYSTEMS_ICC__ > 8)

  #error "<yvals.h>  compiled with wrong (version of IAR) compiler"

#endif

 

I will also put that in the Bugtracker on GitHub

 

Best regards

 

Martin

**Comment by martin-mm** [comment]
Unfortunately still persists - will investigate further.

**Comment by martin-mm** [comment]
again the bugtracker swallowed the leading and trailing two underscores (set to "bold" instead)

**Comment by ErichStyger** [comment]
you can attach files to the ticket system, that would be easier
Erich

**Comment by martin-mm** [comment]
o.k. - here we go :-)
[integer_h.zip](https://github.com/ErichStyger/McuOnEclipse_PEx/files/680104/integer_h.zip)

**Comment by ErichStyger** [comment]
Many thanks! It is now pushed: https://github.com/ErichStyger/McuOnEclipse_PEx/commit/15f6c6bf9c27d8f17532565f559e5bfd4e24d7be

I have a look at https://github.com/ErichStyger/McuOnEclipse_PEx/issues/23 later today.
