### ISSUE TITLE
IAR problem: IAR complains about casting a function pointer to void * in CLSx.c

### ISSUE THREAD

**Issue by martin-mm** [ErichStyger/McuOnEclipse_PEx#23]
IAR complains about casting a function pointer to void * (seems that GCC is more relaxed here)

CLSx.c:

unsigned CLS1_printfIO(CLS1_ConstStdIOType *io, const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS1_printfPutChar, io->stdOut, fmt, args);
  va_end(args);
  return count;
}

Here IAR complains about casting a function pointer to void * (seems that GCC is more relaxed here)

Should be casted in the CLSx.c:

unsigned CLS1_printfIO(CLS1_ConstStdIOType *io, const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS1_printfPutChar, (void *)(io->stdOut), fmt, args);
  va_end(args);
  return count;
}

as well:

unsigned CLS1_printf(const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS1_printfPutChar, (void *)(CLS1_GetStdio()->stdOut), fmt, args);
  va_end(args);
  return count;
}

**Comment by ErichStyger** [comment]
fixed now as well: https://github.com/ErichStyger/McuOnEclipse_PEx/commit/a9c293a2ead8a004b766147bf70a188eb1cd5b98

Thank you!
