### ISSUE TITLE
KDS_3.1.0 + 12-Dec-2016 Components

### ISSUE THREAD

**Issue by mstroven** [ErichStyger/McuOnEclipse_PEx#25]
With the latest MCUonEclipse PEx components, I am getting an error with the Generated Code paths for my components.  It looks like they want multiple back-slashes.  I have not had this problem in the past, but I haven't updated components in a few months.
This is running KDS_3.1.0 on Mac OS X.
--------------- Start Copied Text ----------------
Description	Resource	Path	Location	Type
Generator: FAILURE: at line 1012: {{DEVELOPMENT}} Invalid file/directory specified, driver required "Generated_Code\ \XF1config.h", but currently used Generated_Code\XF1config.h (file: Drivers\sw\XFormat.drv)	FRDM_KE06_Serial_Demo		XF1	Processor Expert Problem
---------------- End Copied Text -----------------

**Comment by mstroven** [comment]
The markdown viewer is automatically converting multiple '\' characters to one, so I inserted a space in the above Issue entry.  Be aware that no space exists in the actual error.

**Comment by ErichStyger** [comment]
Thanks for reporting this, I'm in the process of fixing it.
You can turn off the errors as they come from a 'debug' setting:
Window > Preferences > Processor Expert > Component Development Environment  and then disable the 'Enable Processor Expert Components Debug Verbose Mode'

**Comment by ErichStyger** [comment]
I have applied fixes and pushed the fix:
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/669848aa0477d23ae9a5b7f3f6017a8b98ad04d0

**Comment by mstroven** [comment]
Hello Erich, 
Thanks for the quick reply! 

-Mike
