### ISSUE TITLE
Freescale USB Stack V4.1.1

### ISSUE THREAD

**Issue by armgomes** [ErichStyger/McuOnEclipse_PEx#26]
Hi Erich! 
First all I'd like say thank you for your website https://mcuoneclipse.com/! Your informations and tips are very important for me and many people around the world! 

I tryed to use the Freescale USB Stack v4.1.1 but unfortunately doesn't worked, for many reasons. Well, I found your post "https://mcuoneclipse.com/2012/10/07/tutorial-usb-cdc-with-the-kl25z-freedom-board/", over again, your great solution! 

If you could help me I have two questions: 

Do you know why the files (Freescale USB Stack v4.1.1) do not work correctly?
May I used your solution for family KL27 more especificaly for MKL27Z64VFM4?

Regards,

Arnaldo

**Comment by ErichStyger** [comment]
Hi Arnaldo,
to my knowledge, the KL27Z is only supported with the Kinetis SDK (and not with Processor Expert). Because the Kinetis SDK is not compatible with the Processor Expert components, that USB stack does not work with it. I think this the problem you are facing?
Erich

**Comment by armgomes** [comment]
Hi Erich! You right!
Thank you!

Regards,

Arnaldo

2017-01-13 16:14 GMT-02:00 Erich Styger <notifications@github.com>:
