### ISSUE TITLE
portCF_INTC_VALUE not defined for MCF51JE variant in FreeRTOS component

### ISSUE THREAD

**Issue by markdonkers** [ErichStyger/McuOnEclipse_PEx#27]
I believe I have found an issue with the FreeRTOS component. In the component Inspector, under Scheduler > ColdFire V1 > CPU, I select the MCF51JE.

When I rebuild the PEx components and then compile the project, the following call in FRTOS1.c:

`
taskYIELD();
`

.... has the error description that follows:

	Description	Resource	Path	Location	Type
	undefined identifier 'error'	FRTOS1.c	/QG-H1/Generated_Code	line 1659	C/C++ Problem

taskYIELD is defined as portYIELD, which contains portCF_INTC_VALUE, which is defined portmacro.h as:

```
	/* Context switches are requested using the force register. */
	#define portCF_INTC_VALUE \
		#error "unknown ColdFire CPU setting in embedded component properties!"
```

If I change it to another variant, say MCF51MM, it compiles. Is the definition missing for the JE256 variant?

Thanks.

**Comment by ErichStyger** [comment]
Hi Mark,
I appologize not responding. Somehow I have completely missed that ticket :-(. Indeed, you have found an issue I need to look at. I'll respond back as soon as I can.
Erich

**Comment by ErichStyger** [comment]
Hi Mark,
You can safely use the ME variant instead of the JE one. I have implemented a fix (https://github.com/ErichStyger/McuOnEclipse_PEx/commit/dbef8e28b76af208c5af7e5de4cb7dcbdc5d2aba) with a better check for the derivative.
I'm sorry for the troubles this has created for you :-(
Erich

**Comment by markdonkers** [comment]
Hi Erich,

It appears that I have an apology too. Your reply ended up in my "Forums"
filter on Gmail. Thank you for looking into this and fixing the bug. I will
reload our Components.

Thanks again for the time that you offer to the community. Great work!

Regards,
Mark Donkers
