### ISSUE TITLE
FreeRTOS 9.0 bean isn't working on MCF51JM

### ISSUE THREAD

**Issue by celsoken** [ErichStyger/McuOnEclipse_PEx#29]
Dear Erich,
First of all I'd like to thank you for your unvaluable work on FreeRTOS. I was looking for FreeRTOS support for Freescale devices and I've found several samples of your great work.

I've downloaded and installed your PE Beans from repo but it did not work for my CW 10.7 MCF51JM project.
non-LDD SWI option on properties displays "error in inherited component", pls check image:

![non-ldd swi](https://user-images.githubusercontent.com/29979425/27958847-4a12e436-62fb-11e7-86e2-de690772848d.jpg)

I kindly ask you what can I do to proceed: if you can't work on this subject please tell me which version of FreeRTOS is the last working one for MCF51JM.

Thanks in advance and if I can help you pls let me know.

Cheers,
Celso

**Comment by ErichStyger** [comment]
Hi Celso,
thanks for reporting, I'll have a look into it until tomorrow.
Erich

**Comment by ErichStyger** [comment]
I checked it on my side, and everything seems to work fine?
Could it be that you did not assign an interrupt for the SWI?
see attached screenshot.
![swi](https://user-images.githubusercontent.com/3187954/27986245-cc75f8da-63fc-11e7-89eb-874781a28360.png)

Other than that, have a look at my CodeWarrior project for JM128 on GitHub:
https://github.com/ErichStyger/mcuoneclipse/tree/master/Examples/CodeWarrior/DEMOJM

I hope this helps,
Erich

**Comment by ErichStyger** [comment]
Closing issue as I have not received any further information.

**Comment by celsoken** [comment]
Dear Erich,

 

Sorry, I was out in winter vacation and after coming back found a lotta stuff to work with.

But I’ll give it a try this week and I’ll let you know.

Thanks for your time!

Cheers,

Celso

 

Celso Ken Mori Monteiro - Flexmotronics

e-mail:  <mailto:celsokenm@gmail.com> celsokenm@gmail.com

Brusque office phone (GMT-3:00) : +55 (47) 3355 7423

Mobile: +55 (47) 99220 3600 Vivo whatsapp   +55 (47) 99656 7195 TIM

 

De: Erich Styger [mailto:notifications@github.com] 
Enviada em: terça-feira, 1 de agosto de 2017 11:55
Para: ErichStyger/McuOnEclipse_PEx
Cc: celsoken; Author
Assunto: Re: [ErichStyger/McuOnEclipse_PEx] FreeRTOS 9.0 bean isn't working on MCF51JM (#29)

 

Closing issue as I have not received any further information.
