### ISSUE TITLE
RTOS tick timer does not interrupt at configured rate when using ColdFire V1 TPM system.

### ISSUE THREAD

**Issue by markdonkers** [ErichStyger/McuOnEclipse_PEx#31]
When using the TPM system of the ColdFire V1 processor, the tick rate rate does not occur at the configured rate. 

Example:
The 16-bit, 4-channel TPM system has 5 interrupts (4 value match interrupts and an overflow). The FreeRTOS component uses the TPM1_ch0 interrupt as it's tick interrupt (TickCntr1 bean). The TickCntr1 properly configures the TPM1C0V (value) register, but in the interrupt, there is no mechanism to set the time of the next interrupt event. Instead the next event does not occur again until the counter rolls over and hits the value in the channel's VALUE register, which is 65535 counts later. 

Workaround:
In the `FRTOS_vApplicationTickHook()` event, insert code to modify the timing system. For my MCU (whose bus speed is 24 MHz), I use a 1 ms tick rate, therefore the VALUE register must be incremented by 24,000 counts.

```
void FRTOS_vApplicationTickHook(void)
{
    /* Called for every RTOS tick. */
    TPM1C0V += 24000;
}
```

Caveat:
The previous workaround does not take allow for multiple speed modes. If multiple speed modes are present the value would need to be loaded from a table.

**Comment by ErichStyger** [comment]
Hi Mark,
thanks for reporting, I have to check this tomorrow when I have a board at hand.
Erich

**Comment by markdonkers** [comment]
Good afternoon, Erich. 
Were you able to confirm whether this is a bug or not?

Thanks!
Mark

**Comment by ErichStyger** [comment]
Hi Mark,
I'm sorry, I did not find the time to look into this yet.

Erich

**Comment by ErichStyger** [comment]
Hi Mark,
I checked what you say, and I can confirm that it works properly on my side. Not sure what creates the difference for you. You might have a look at my MCF51JM128 project (https://github.com/ErichStyger/mcuoneclipse/tree/master/Examples/CodeWarrior/DEMOJM/DEMOJM_FreeRTOS_MCF51JM128). It uses a 10 ms timer, set for a 10 ms period. The timer is for compare interrupt only (no overflow interrupt) by Processor Expert:

`void TickCntr1_Init(void)
{
  /* TPM1SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=0,PS2=0,PS1=0,PS0=0 */
  setReg8(TPM1SC, 0x00U);              /* Stop HW; disable overflow interrupt and set prescaler to 0 */ 
  /* TPM1MOD: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(TPM1MOD, 0x00U);            /* Clear modulo register: e.g. set free-running mode */ 
  /* TPM1C0SC: CH0F=0,CH0IE=1,MS0B=0,MS0A=1,ELS0B=0,ELS0A=0,??=0,??=0 */
  setReg8(TPM1C0SC, 0x50U);            /* Set output compare mode and enable compare interrupt */ 
  EnUser = FALSE;                      /* Disable device */
  TickCntr1_SetCV(0xA3D7U);            /* Initialize appropriate value to the compare/modulo/reload register */
  clrSetReg8Bits(TPM1SC, 0x07U, 0x00U); /* Set prescaler */
  HWEnDi();
}
`

Component settings:
- Interrupt: enabled
- Period/offset: 10 ms
- Reset counter on compare: no
- Same period in modes: yes
- component uses entire timer: yes

Can you confirm?
Thanks,
Erich

**Comment by markdonkers** [comment]
Hi Erich,

Your TickCntr1_Init() function matches mine, except for the Period/Offset
value of course. As well, the component settings that you stated are also
the same.

I downloaded, imported and built the example project and it generated the
same code.

My next step is to take a closer look at the documentation for the TPM and
a closer look at my project.

Thanks Erich.

Mark

**Comment by markdonkers** [comment]
Hi Erich,

Oh yes, I had already trusted that your target is operating correctly. That
was not in question. It seems obvious that there is something wrong on my
end.

Thanks,
Mark

**Comment by ErichStyger** [comment]
Closing issue as I believe it is resolved.
