### ISSUE TITLE
FreeRTOS: Add mechanism to implement "Trace Hook Macros"

### ISSUE THREAD

**Issue by markdonkers** [ErichStyger/McuOnEclipse_PEx#32]
We would like to define our own implementation of FreeRTOS' `traceTASK_SWITCHED_OUT()` and `traceTASK_SWITCHED_IN()` macros in order to instrument our RTOS' behaviour. According to the documentation at [Trace Hook Macros](https://www.freertos.org/rtos-trace-macros.html):

> Macro definitions must occur before the inclusion of FreeRTOS.h. The easiest place to define trace macros is at the bottom of FreeRTOSConfig.h, or in a separate header file that is included from the bottom of FreeRTOSConfig.h.

We have included a header file at the bottom FreeRTOSConfig.h, but this inclusion is removed each time the FreeRTOS component is regenerated. 

Is there already a mechanism that will allow the use of custom trace macros? If not, does a property or setting need to added to the FreeRTOS component?

Of course, I could disable Code Generation, but that does not seem logical since it isn't really a "tweak" of the generated code.

Thanks for any assistance and/or insight.

**Comment by ErichStyger** [comment]
Hi Mark,
I have made a change to support your use case here:
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/10190a479cdc22661a9562a97960df364d87400e

I have as well sent you that component by email.
Simply re-open that ticket if that does not work for you.
Thanks for that great suggestion!
Erich

**Comment by markdonkers** [comment]
Hi Erich,

Amazing! Thank you for performing that update!

I'll try it out and let you know.

Mark
