### ISSUE TITLE
MKE02Z64VQH4 UART issue

### ISSUE THREAD

**Issue by addelichtman** [ErichStyger/McuOnEclipse_PEx#33]
Hello,
I am writing code for the mentioned processor using ECLIPSE Kinetis Design Studio
Version: 3.2.0 with Processor Expert.
I am presently working with the AsynchroSerial component.
The following issue occurs.
In 20% of the received serial messages the AS1_OnError(void) event is triggered. If I examine the error with function AS1_GetError() I always find the error to be "OverRun". If I examine the buffer with AS1_GetCharsInRxBuf() the count is 0. I am breaking my head over what could cause this phenomena. Could you please help me?
Kind regards Ad.

**Comment by ErichStyger** [comment]
Have you turned on the Interrupt setting with say 64 bytes of buffer size? this is what I recommend.

**Comment by addelichtman** [comment]
Hello Mr. Styger, 
Thank you for the very prompt answer.
I already set the buffer sizes to 255 bytes, do you have other recommendations?
Thanks Ad

**Comment by ErichStyger** [comment]
Check with an oscilloscope your RX/TX lines: if you have noise then the UART might see more data than it really has.
Set the buffer size to 512 (255 was a bug in the component a while ago).
Check your interrupts: it could be that you are blocking them for too long, that way the UART is not able to serve them properly. Ultimately, the AsynchroSerial component is not written by me, but by Freescale/NXP, so I don't have any  control over it.

**Comment by addelichtman** [comment]
Hello Mr. Styger I checked the quality of the signals with a scope they are fine.
Tried to change buffer sizes but that will not solve the problem.
I checked the interrupts but everything seems ok.
Whom can I contact for further questions?
Thank you very much for your bather.
Kind regards Ad

**Comment by ErichStyger** [comment]
Hi Ad,
from remote it is really hard to tell what is going on. I suggest you build a reproducible case and post it in the NXP community maybe?

Erich
