### ISSUE TITLE
Processor Expert for HCS08PL16S part number 

### ISSUE THREAD

**Issue by Croby80** [ErichStyger/McuOnEclipse_PEx#35]
Good morning, I need to program an HCS08 PLS16 device and I installed CodeWarrior for MCU v11.1 Build ID : 181224

and I need to use Processor expert but it seems not to function correctly: I see component for PL16S but I'm not able to build up project with that device and environment seems to be broken... I attached the error log of installed components:

[EclipseErrorLog.txt](https://github.com/ErichStyger/McuOnEclipse_PEx/files/6647442/EclipseErrorLog.txt)

thank you

**Comment by ErichStyger** [comment]
Hi,
I checked my installation, and I do have a HCS08 PL16 (not that PLS16 or PL16S you are referring too). Plus my Processor Expert in MCU V11.1 (same build ID as yours), but it does not offer in the wizard to create a PL16 project for me. The MC9S08PL16 is listed as CPU component.
So there seems to be some support, but it is not complete in my view. How did you create your project?

**Comment by ErichStyger** [comment]
Was able to create a PEX project for PL16. So here is what I did:

1. created bare metal project
2. Enabled Processor Expert for it (see https://mcuoneclipse.com/2014/01/19/diy-free-toolchain-for-kinetis-part-8-processor-expert-eclipse-and-gnu-arm-eclipse-plugins/)
3. Project > Clean
4. removing the backup of main
5. build
that worked (at least I'm able to compile

**Comment by Croby80** [comment]
Now, I verified, with Processor Expert I'm able to manage PL16 but not PL16S part number. The last one is not supported? 

Thank you for your help! 

Roberto Casella 
Electronic R&D Department 


Da: "Erich Styger" ***@***.***> 
A: "ErichStyger/McuOnEclipse_PEx" ***@***.***> 
Cc: "Roberto Casella" ***@***.***>, "Author" ***@***.***> 
Inviato: Lunedì, 14 giugno 2021 17:28:38 
Oggetto: Re: [ErichStyger/McuOnEclipse_PEx] Processor Expert for HCS08PL16S part number (#35) 





Was able to create a PEX project for PL16. So here is what I did: 

    1. created bare metal project 
    2. Enabled Processor Expert for it (see [ https://mcuoneclipse.com/2014/01/19/diy-free-toolchain-for-kinetis-part-8-processor-expert-eclipse-and-gnu-arm-eclipse-plugins/ | https://mcuoneclipse.com/2014/01/19/diy-free-toolchain-for-kinetis-part-8-processor-expert-eclipse-and-gnu-arm-eclipse-plugins/ ] ) 
    3. Project > Clean 
    4. removing the backup of main 
    5. build that worked (at least I'm able to compile

**Comment by ErichStyger** [comment]
If PL16S is not listed, then I think it is not supported. I don't know the difference between the S and non-S part, but maybe you could use the PL16 for the PL16S?

**Comment by Croby80** [comment]
I must deeply verify differences, I think I can start with PL16 and after manually to add changes. Thank you for your fast answer. 

Roberto Casella 
Electronic R&D Department 


Da: "Erich Styger" ***@***.***> 
A: "ErichStyger/McuOnEclipse_PEx" ***@***.***> 
Cc: "Roberto Casella" ***@***.***>, "Author" ***@***.***> 
Inviato: Martedì, 15 giugno 2021 8:20:10 
Oggetto: Re: [ErichStyger/McuOnEclipse_PEx] Processor Expert for HCS08PL16S part number (#35) 





If PL16S is not listed, then I think it is not supported. I don't know the difference between the S and non-S part, but maybe you could use the PL16 for the PL16S?
