### ISSUE TITLE
nand flash controller (nfc) issue

### ISSUE THREAD

**Issue by HEMODIA85** [ErichStyger/McuOnEclipse_PEx#36]
Hello,
i'm using a nand flash in one of our projects. the refernce is MT29f2g08
i'm using Processor expert within KDS to manipulate my project,
i used and configured the drivers nfc_ldd provided by processor expert 
i have some probems when i use the differnt functions such as nfc1_READID, nfc1_RESET, .... These functions return 0x08 which means ERR BUSY
i put a screen shot of my IDE with the comping results
Would you like to tell me how can i use thease functions correctely?
Thanks in advance,
Best regards,
![Capture](https://user-images.githubusercontent.com/105505552/168312436-1837031a-b2b5-49ac-a1fb-88cd1bc0989f.JPG)
[Desktop.zip](https://github.com/ErichStyger/McuOnEclipse_PEx/files/8688932/Desktop.zip)

**Comment by ErichStyger** [comment]
I'm sorry, but I did not wrote that NFC component. You would need to get in touch with NXP about this.
