### ISSUE TITLE
Error generating code for GenericSWSPI in KDS 3.0.0

### ISSUE THREAD

**Issue by eatcircuits** [ErichStyger/McuOnEclipse_PEx#7]
I imported the Processor Expert Components Part1_Beans_22.03.2015.PEupd and Part2_Beans_22.03.2015.PEupd into KDS 3.0.0

I imported an existing project created in KDS2.0 into KDS 3.0.0
The contains a component GenericSWSPI.
While generating the Processor Expert Code I get the following errör:

Generator: FAILURE: at line 276: Error in including "Drivers\Common\SynchroMasterSetIdleClockPolarity.Inc" from directory C:\Users\JohnSimeon\MyComponents (file: Drivers\sw\GenericSWSPI.drv)
Generator: FAILURE: at line 548: Error in including "Drivers\Common\SynchroMasterSetIdleClockPolarity.Inc" from directory C:\Users\JohnSimeon\MyComponents (file: Drivers\sw\GenericSWSPI.drv)

**Comment by ErichStyger** [comment]
Hello,
many thanks for reporting this, and I confirm the issue :-(. Must have been some copy-paste error, so I appologize for that.
I have committed a fix here:

It will be included in the upcoming release.

**Comment by ErichStyger** [comment]
sorry, missed to provide the link to the commit:
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/a9e5f50555072bb136e34b41a777fc6eba15a453

**Comment by eatcircuits** [comment]
Thanks Erich. Your blog has been of much help to me. Thanks again for the fix.
