### ISSUE TITLE
SD Card SPI disable on speed change

### ISSUE THREAD

**Issue by MattGeerts** [ErichStyger/McuOnEclipse_PEx#8]
In SD1.c the function SD1_SetFastMode contains:

void SD1_SetFastMode(void)
{
  SD1_SPI_Disable();
  SD1_SPI_SetFastMode();                /* the SPI clock is set to the maximum supported by the MCU and allowed by the SD card */
  speedMode = SD1_ACTIVATE_MODE_FAST;
  SD1_SPI_Enable();
}

The SD1_SPI_Disable function sets the enable flag to false:
((SM1_TDeviceDataPtr)DeviceDataPtr)->EnUser = FALSE;

Then the SD1_SPI_SetFastMode() function checks to see if it is false and throws an error:
if (!((SM1_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }

So the SD1_SetFAstMode sets itself up to fail, the result being that it never goes to fast mode. The same is true of SetSlowMode, but it doesn't matter because it defaults to slow mode on startup.

I see a comment in SM1_SelectConfiguration (which is the aliased call from SD1_SPI_SetFastMode) that says this can be ignored, but I can't find a place in PE with the ignore setting mentioned:
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */

**Comment by ErichStyger** [comment]
Hi Matt,
thanks for reporting this. Indeed, this is an issue if using the LDD drivers. I'm working on a fix.
Erich

**Comment by MattGeerts** [comment]
Erich,

The "thanks" is all yours. Your website and drivers are making my life much easier. 

-Matt

**Comment by ErichStyger** [comment]
Hi Matt,
thank you for that, feeling a little bit better now :-)
I have implemented a fix and committed it:
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/5b1212d0533c5456471fe7677f39d9ea7ff203fc

The only problem I have is: I'm not sure any more why I had to disable the SPI around changing the speed. I have tested it now on two Kinetis boards, one with LDD SPI and one normal SPI, and it works fine with that change. As a bonus, the LDD version is now about 4-5 times faster than before (FRDM-K64F with microSD card):
'old version':
CMD> Benchmark: open file, write 10k times 10 bytes (100'000 bytes), close file:
Deleting existing benchmark files...
Creating benchmark file...
3100 ms needed for creating.
Reading benchmark file...
2810 ms needed for reading.
Copy file (100'000 bytes)...
6070 ms needed for copy.
done!

New version: 
CMD> FAT1 benchmark
Benchmark: open file, write 10k times 10 bytes (100'000 bytes), close file:
Deleting existing benchmark files...
Creating benchmark file...
2680 ms needed for creating.
Reading benchmark file...
2360 ms needed for reading.
Copy file (100'000 bytes)...
4940 ms needed for copy.
done!
 
Erich

**Comment by ErichStyger** [comment]
Let me know if you need the .bean file. Simply reopen the ticket if there is still a problem.

Thanks again!

**Comment by MattGeerts** [comment]
Thanks Erich!

I have not yet learned to change source into beans, so if you can send the bean to "mgeerts" at "trojanuv" dot "com" I'll test it out on Monday!

**Comment by ErichStyger** [comment]
![sd_card_08 08 2015 peupd](https://cloud.githubusercontent.com/assets/3187954/9149628/09d2ccac-3db3-11e5-8811-d5d2d7217a77.png)

**Comment by MattGeerts** [comment]
Downloaded, installed, tested, working.

Thanks again, Erich.
