### ISSUE TITLE
SEGGER_RTT RTT_WriteString bug

### ISSUE THREAD

**Issue by Tironis** [ErichStyger/McuOnEclipse_PEx#9]
RTT_WriteString seems to be missing a parameter: no BufferIndex is supplied.

I do see that the components was updated as recently as 20 minutes ago, but didn't see anything regarding this issue in there. Apologies if I'm re-reporting. Is this the preferred avenue for reporting such things?

**Comment by ErichStyger** [comment]
Thanks for pointing out that problem and for reporting. Yes, using the GitHub ticketing is exactly meant for reporting this kind of things :-)
Fixed now in this commit: 
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/c1351aa2dd281a67e54ffa56cd8f87dab5cf982c
